#--------------------------------------------------
# Site settings
#--------------------------------------------------
theme: minima
title: Another IT Blog
author: subnetspider
lang: en
icon: ðŸ˜ˆ

#--------------------------------------------------
# Social Media
#--------------------------------------------------
github_username: subnetspider
twitter_username: subnetspider
mastodon:
- username: subnetspider
  instance: mastodon.bsd.cafe

#--------------------------------------------------
# General options
#--------------------------------------------------
#url-pretty: "subnetspider.com"

exclude:
  - CNAME
  - LICENSE
  - README.md
