#--------------------------------------------------
# Site settings
#--------------------------------------------------
remote_theme: "jekyll/minima@1e8a445"
title: subnetspider.com
author: subnetspider
lang: en
icon: ğŸ˜ˆ

#--------------------------------------------------
# Social Media
#--------------------------------------------------
github_username: subnetspider
twitter_username: subnetspider
mastodon:
- username: subnetspider
  instance: mastodon.bsd.cafe

#--------------------------------------------------
# General options
#--------------------------------------------------
#url-pretty: "subnetspider.com"

exclude:
  - CNAME
  - LICENSE
  - README.md

switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

minima:
  skin: dark
