#--------------------------------------------------
# Site settings
#--------------------------------------------------
theme: minima
title: Subnetspider's Blog
author: subnetspider
lang: en
icon: ðŸ˜ˆ

#--------------------------------------------------
# Social Media
#--------------------------------------------------
social-network-links:
  github_username: subnetspider
  twitter_username: subnetspider

#--------------------------------------------------
# General options
#--------------------------------------------------
url-pretty: "subnetspider.com"

exclude:
  - CNAME
  - LICENSE
  - README.md
